#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import re
import sqlite3

# Load press info into db

# About: script to load press data into an sqlite3 db from a text file

conn = sqlite3.connect(sys.argv[1])
conn.text_factory = str
c = conn.cursor()

# clear database
c.execute('DELETE FROM press WHERE id>=1')

counter = 1 

with open(sys.argv[2], "r") as f:
	for line in f:
		# if line not empty
		if (line.strip()):

			line = line.rstrip('\n')
			# try parsing to get url, doi
			match = re.search(r'<a href="(.*)">(.*)<(.*)', line)
			if (match):
				year = 0

				match2 = re.search(r', (\d{4})$', match.group(2))
				if (match2):
					year = match2.group(1)

				l = (counter, year, match.group(2), match.group(1))

				print(l)

				c.execute('INSERT INTO press (id, year, mytext, journal_url) VALUES (?,?,?,?)', l)

			# Save (commit) the changes
			conn.commit()

			# increment
			counter += 1

# here's the schema I'm depositing data into:

# create table press (
#   id integer primary key autoincrement,
#   year integer not null,
#   mytext text not null,
#   title text,
#   journal_url text
# );

# We can also close the connection if we are done with it.
# Just be sure any changes have been committed or they will be lost.
conn.close()
