#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import re
import sqlite3

# Load motor neuron data into db

# About: script to load motor data into an sqlite3 db from a text file

conn = sqlite3.connect(sys.argv[1])
conn.text_factory = str
c = conn.cursor()

# clear database
c.execute('DELETE FROM motor WHERE id>=1')

counter = 1 

with open(sys.argv[2], "r") as f:
	for line in f:
		# if line not empty
		if (line.strip()):

			line = line.rstrip('\n')

			l = tuple([counter] + line.split())

			c.execute('INSERT INTO motor (id, Gene, Cells, Mean, Min, Max, Connectivity, p_value, BH_p_value, Centroid, Dispersion, RNA_binding, Splicing, Surface, Transcription) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', l)

			# Save (commit) the changes
			conn.commit()

			# increment
			counter += 1

conn.close()
